pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('Projects/project_1') {
                    sh '''
                        docker build \
                            -t shonk673/flask-app:latest \
                            .
                    '''
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    docker run --rm \
                        shonk673/flask-app:latest \
                        pytest
                '''
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry(
                        'https://index.docker.io/v1/',
                        'dockerhub-creds'
                    ) {
                        sh '''
                            docker push shonk673/flask-app:latest
                        '''
                    }
                }
            }
        }
    }
    post {
        success {
            emailext(
                to: 'shounakkannaik1234@gmail.com',
                subject: "✅ ${env.JOB_NAME} #${env.BUILD_NUMBER} - SUCCESS",
                body: """
            Build successful!

            Job: ${env.JOB_NAME}
            Build: #${env.BUILD_NUMBER}

            Docker image:
            shonk673/flask-app:latest

            Build URL:
            ${env.BUILD_URL}
            """
                        )
                    }

                    failure {
                        emailext(
                            to: 'shounakkannaik1234@gmail.com',
                            subject: "❌ ${env.JOB_NAME} #${env.BUILD_NUMBER} - FAILED",
                            body: """
            Build FAILED!

            Job: ${env.JOB_NAME}
            Build: #${env.BUILD_NUMBER}

            Build URL:
            ${env.BUILD_URL}
            """
            )
        }
    }
}
