pipeline {
    agent any
    stages {

        stage('Show Repository Structure') {
            steps {
                sh '''
                    echo "=== CURRENT DIRECTORY ==="
                    pwd

                    echo "=== TOP LEVEL ==="
                    ls -la

                    echo "=== DIRECTORIES ==="
                    find . -maxdepth 3 -type d | sort

                    echo "=== DOCKERFILES ==="
                    find . -name Dockerfile -print

                    echo "=== JENKINSFILES ==="
                    find . -name Jenkinsfile -print
                '''
            }
        }
    }
}